name: Terraform Plan
on:
  # pull_request:
  #   branches:
  #     - main
  push:
    branches:
      - dev
# Need ID token write permission to use OIDC
permissions:
  id-token: write
jobs:
  authenticate:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.2.3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ca-central-1
      - name: Additional steps
        run: |
          # Your commands that require AWS credentials
          aws sts get-caller-identity